version: "3.8"

services:
#MariaDB Container
  database:
    image: mariadb:10.7
    networks:
      - backend
    volumes:
      - database:/var/lib/mysql
    env_file:
      - ./mariadb.env
    restart: always

#GLPI Container
  app:
    build: .
    networks:
      - backend
    ports:
      - "8181:80"
    env_file:
      - ./glpi.env
    restart: always

networks:
  backend:
    driver: overlay
    attachable: false

volumes:
  database:
  files:
  plugins: